sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t alex/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alex/docker-react npm run test a -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY